gmetad:
    build: ./gmetad 
    working_dir: /code
    command: python test.py
    volumes: 
        - ./gmetad_conf:/etc/ganglia/
        - .:/code
    ports:
        - "8000:8000"
    links:
        - gmond1
        - gmond2
        - gmond3
        - gmond4

gmond1:
    build: ./gmond 
    command: /usr/sbin/sshd -D
    volumes: 
        - ./gmond_conf:/etc/ganglia/

gmond2:
    build: ./gmond
    command: /usr/sbin/sshd -D
    volumes: 
        - ./gmond_conf:/etc/ganglia/
        
gmond3:
    build: ./gmond
    command: /usr/sbin/sshd -D
    volumes: 
        - ./gmond_conf:/etc/ganglia/

gmond4:
    build: ./gmond
    command: /usr/sbin/sshd -D
    volumes: 
        - ./gmond_conf:/etc/ganglia/
